[theme]
base="dark"
primaryColor="#ff69b4"
backgroundColor="#0f0f15"
secondaryBackgroundColor="#222"
textColor="#ffffff"
font="sans serif"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
hideSidebarNav = true
